version: "3.3"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "${DB_USER}"
      # You can use whatever password you like
      MYSQL_PASSWORD: "${DB_PASS}"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "${DB_EXPOSED_PORT}:${DB_INTERNAL_PORT}"
    expose:
      # Opens port 3306 on the container
      - "${CONTAINER_PORT}"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db:
